create models and admin
tach-by/MyDjangoProject pull request #2
Opened 2024-02-15 01:10 UTC by tach-by

Task. 26
Your task is to create models and configure an admin panel to manage projects and tasks. The Project model should be a project with the name, description, and creation date fields. The Task model must be a project-specific task with the fields of name, description, status and priority. 
The Admin Panel should provide convenient management of projects and tasks, including creating, editing, and deleting records.

2024-02-15 09:27 UTC, pareikoVladislav requested changes

2024-02-15 09:27 UTC, pareikoVladislav commented on apps/project/models.py
> +    STATUS_CHOICES = [
Лучше определяй подобные константы вне модели. В модели прописываем конкретно поля.

2024-02-15 09:27 UTC, pareikoVladislav commented on apps/project/models.py
> +    PRIORITY_CHOICES = [
так же.

2024-02-15 17:11 UTC, tach-by commented on apps/project/models.py
> +    STATUS_CHOICES = [
done

2024-02-15 17:12 UTC, tach-by commented on apps/project/models.py
> +    PRIORITY_CHOICES = [
done

2024-02-16 08:56 UTC, pareikoVladislav approved these changes

2024-02-16 13:16 UTC, merged